### ISSUE TITLE
cann't work with webpack 

### ISSUE THREAD

**Issue by moyuming** [nicholaslee119/webpack-component-loader#5]
test\testInWebpack.test.js is not  success，why？

**Comment by nicholaslee119** [comment]
Hi, there,
Thanks for your report, and I have tried to reproduce it but everything goes fine on my computer
Could you please give me some more information about that?
For example, your environment and the detail of the error and something like that.

**Comment by moyuming** [comment]
platform : window 7
node version : 8.11.3
npm version :6.4.1
follow is the error of running the script 'npm run test'





------------------ 原始邮件 ------------------
发件人: "Nicholas Lee"<notifications@github.com>;
发送时间: 2019年3月18日(星期一) 上午10:52
收件人: "nicholaslee119/webpack-component-loader"<webpack-component-loader@noreply.github.com>;
抄送: "罗曼蒂克"<347307741@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [nicholaslee119/webpack-component-loader] cann't work withwebpack  (#5)




Hi, there,
 Thanks for your report, and I have tried to reproduce it but everything goes fine on my computer
 Could you please give me some more information about that?
 For example, your environment and the detail of the error and something like that.

**Comment by moyuming** [comment]
> webpack-component-loader@1.0.10 test E:\node-project\webpack-component-loader-
master
> jest

 FAIL  test\testInWebpack.test.js
  ● test in webpack › should be built successfully in webpack

    expect(received).toBeTruthy()

    Expected value to be truthy, instead received
      false

      at cb (test/testInWebpack.test.js:22:24)
      at emitRecords.err (node_modules/webpack/lib/Compiler.js:265:13)
      at Compiler.emitRecords (node_modules/webpack/lib/Compiler.js:371:38)
      at emitAssets.err (node_modules/webpack/lib/Compiler.js:258:10)
      at applyPluginsAsyncSeries1.err (node_modules/webpack/lib/Compiler.js:364:
12)
      at next (node_modules/tapable/lib/Tapable.js:218:11)
      at Compiler.compiler.plugin (node_modules/webpack/lib/performance/SizeLimi
tsPlugin.js:99:4)
      at Compiler.applyPluginsAsyncSeries1 (node_modules/tapable/lib/Tapable.js:
222:13)
      at Compiler.afterEmit (node_modules/webpack/lib/Compiler.js:361:9)
      at require.forEach.err (node_modules/webpack/lib/Compiler.js:350:15)
      at node_modules/async/dist/async.js:473:16
      at iteratorCallback (node_modules/async/dist/async.js:1064:13)
      at node_modules/async/dist/async.js:969:16
      at node_modules/graceful-fs/graceful-fs.js:111:16
      at node_modules/graceful-fs/graceful-fs.js:45:10
      at FSReqWrap.oncomplete (fs.js:135:15)

 PASS  test\buildTemplate.test.js
 PASS  test\createOutput.test.js
 PASS  test\findScopedSelectors.test.js
 PASS  test\parsePage.test.js
 PASS  test\setScope.test.js
 PASS  test\genScopeID.test.js

Test Suites: 1 failed, 6 passed, 7 total
Tests:       1 failed, 11 passed, 12 total
Snapshots:   0 total
Time:        2.58s
Ran all test suites.
-------------------------|----------|----------|----------|----------|----------
---------|
File                     |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered
 Line #s |
-------------------------|----------|----------|----------|----------|----------
---------|
All files                |    74.81 |    56.25 |       64 |    75.81 |
         |
 lib                     |       96 |       75 |      100 |    95.83 |
         |
  buildTemplate.js       |    83.33 |       50 |      100 |    83.33 |
       7 |
  core.js                |      100 |      100 |      100 |      100 |
         |
  createOutput.js        |    94.12 |     62.5 |      100 |    94.12 |
      17 |
  findScopedSelectors.js |      100 |      100 |      100 |      100 |
         |
  genScopeID.js          |      100 |      100 |      100 |      100 |
         |
  parsePage.js           |      100 |    83.33 |      100 |      100 |
      24 |
  rewriteTemplate.js     |     87.5 |       75 |      100 |    86.67 |
   16,19 |
 lib/addScopeIDToCSS     |        0 |        0 |        0 |        0 |
         |
  index.js               |        0 |        0 |        0 |        0 |... ,9,10,
12,18,20 |
  scopeIdPlugin.js       |        0 |        0 |        0 |        0 |... 15,16,
17,19,24 |
 lib/utils               |      100 |      100 |      100 |      100 |
         |
  reportError.js         |      100 |      100 |      100 |      100 |
         |
-------------------------|----------|----------|----------|----------|----------
---------|
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webpack-component-loader@1.0.10 test: `jest`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webpack-component-loader@1.0.10 test script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2019-03-18T0
5_58_57_781Z-debug.log
